#Open API - Swagger
name: "@name@"
description: "@description@"
version: "@version@"

spring:
  profiles:
    active: dev
  activemq:
    broker-url: tcp://drhel8labplat001v.sefnet.rj:61616
    password: 123456
    user: emailCorp

jwt:
  expiration: ${SSA_JWT_DURATION:43200000} # 12hs
  secret: ${SSA_JWT_SECRET:JWTuR2yAi7O5UbLfsm9alp7qicsA3KNdrHYSSA}

ssa:
  secret: ${SSA_SECRET:uR2yAi7O5UbLfsm9alp7qicsA3KNdrHY}
  url: ${SSA_URL:http://ssadci.sefnet.rj/ssa}

cors:
  mapping: "/**"
  origins: "**"
  methods: "*"
  headers: "*"

springdoc:
  show-actuator: false
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

email:
  corp:
    mq:
      queue: emailCorp.email   
    file_dir: /tmp/arquivos/saida   